### ISSUE TITLE
Show parents operators in category operators in the documentation

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama-platform.github.io#104]
Currently, the documentation show only operators from the same level for the categories. For example, in "list operators", we can find list-related operators, but no container-related operators:

![image](https://user-images.githubusercontent.com/18676913/166877408-dfe1b6fd-1d79-4c0d-82b1-6974c4511053.png)

However, it might be interesting for users (more specifically beginners) to have somewhere a link to the container operators.

![image](https://user-images.githubusercontent.com/18676913/166877566-127036fa-aea9-432b-b9ef-61d772ab9670.png)

**Comment by RoiArthurB** [comment]
I see the idea, but your example doesn't work if you reverse it : From the *Containers-related operators* we could make link to list too, but also to *Color* (with `mean`, `median`), to *Statistical* (with `min`, `median`), to *Random* or *String* (with `shuffle`) etc...

So I think that (1) generating it (as this page is) will just be confusing and link to everything or (2) may not help that much newcomers without further explanation (list and containers are not always close concepts, so they may not understand this link) and, finally, (3) everything is on the same page, so I'm afraid it just gonna create more links/info without great benefices from this...

Tell me what you think; otherwise I'll close without fixing :)
