### ISSUE TITLE
Some examples have broken formatting

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#120]
**Describe the bug**
On the website, certain examples are formatted as being on only one line whilst they are described as multiple lines in the code used to generate it.
For example here in the doc:
![image](https://user-images.githubusercontent.com/6374469/186823689-b619f8e2-2fa7-4ac6-9293-dc60a3aab6a9.png)
And the code:
![image](https://user-images.githubusercontent.com/6374469/186823879-b60cd1e6-6d99-405c-acee-8de370d8dda8.png)
As of now, I found those cases, maybe there are more:
  * https://gama-platform.org/wiki/next/Statements#usages-2 
  * https://gama-platform.org/wiki/next/Statements#usages-67
  * https://gama-platform.org/wiki/next/Statements#usages-71

In addition, for the `add` documentation, on the website, you can also see a little bit under the first broken example, that some examples are completely empty.
![image](https://user-images.githubusercontent.com/6374469/186824403-ed8d2880-0a1c-4af2-a11e-83f578e6c89e.png)
the code:
![image](https://user-images.githubusercontent.com/6374469/186824472-3d22cf1d-07fc-44d7-bf32-74f40f26119f.png)

Edit: A third formatting problem for examples: sometimes there is a carriage return inserted in the first line that is also not present in the code.
![image](https://user-images.githubusercontent.com/6374469/186833085-f66ae299-7d80-41f1-834e-410983d5b762.png)
Identified cases:
  * https://gama-platform.org/wiki/next/Statements#usages-16
  * https://gama-platform.org/wiki/next/Statements#usages-28
  * https://gama-platform.org/wiki/next/Statements#usages-38
  * https://gama-platform.org/wiki/next/Statements#usages-48
  * https://gama-platform.org/wiki/next/Statements#definition-80
  * https://gama-platform.org/wiki/next/Statements#usages-82
  * https://gama-platform.org/wiki/next/Statements#usages-83
  * https://gama-platform.org/wiki/next/Statements#usages-95
  * https://gama-platform.org/wiki/next/Statements#usages-98

**Comment by RoiArthurB** [comment]
Hello,

As displayed at the top of the page, this page is generated and the bug is not specific to the website :) 
![image](https://user-images.githubusercontent.com/16764085/187145708-edca53ab-bd95-4681-815c-31028229f940.png)

And, even if the generation works smootly on other parts of this page, all the code block is generated on a single line as this :

```
* Case of a list, the expression in the facet at: should be an integer.

`` ` 
list<int> workingList <- [];add 0 at: 0 to: workingList ;//workingList equals [0]add 10 at: 0 to: workingList ;//workingList equals [10,0]add 20 at: 2 to: workingList ;//workingList equals [10,0,20]add 50 to: workingList;//workingList equals [10,0,20,50]add [60,70] all: true to: workingList;//workingList equals [10,0,20,50,60,70]
`` `
```
This should be a bug in the way documentation is generated (maybe an evolution in the generator ?)

---

About the empty code block, here's what the generated markdown display : 

```
`` `add "val2" to: workingMap;//workingMap equals ["x"::"val1", "val2"::"val2"]add "5"::"val4" to: workingMap; //workingMap equals ["x"::"val1", "val2"::"val2", "5"::"val4"]
`` `
```

Here, the problem comes from the code line being on the same line as the code block header. This space is used by Docusaurus to get meta-data for the code block (like setting the language, etc). So the generation should ensure writting code on a different line than the code-block wrapper

---

The last problem still comes from the generator inserting an empty line in the code block as there : 
```
* Other examples of use: 
`` `
 
coping emotion: new_emotion("fear") when: flip(0.5) new_desire: new_predicate("test");
`` ` 
```

Code block won't assume nor prevent anything inside the wrapper and will display extra empty lines if you add some inside. So it have to be prevented during the generation :)

**Comment by lesquoyb** [comment]
Everything seems solved, thanks
