### ISSUE TITLE
Open Street Map documentation page update for QGIS v3

### ISSUE THREAD

**Issue by erralb** [gama-platform/gama-platform.github.io#125]
**Is your request related to a problem? Please describe.**
The GAMA documentation page about [manipulating Open Street Map data](https://gama-platform.org/wiki/ManipulateOSMDatas) is missing a part for QGIS v3.

**Describe the solution you'd like**
A detailed description of the steps for generating Shapefiles from OSM & QGIS v3 with the QGIS OSM plugin (the default QGIS export has been removed in QGIS v3) and exporting to QSpatiaLite, and then how to import and use them in GAMA.

**Additional context**
For a non experienced QGIS user like me, it would be great to document a full example extracting roads, buildings, terrains and backgrounds, with a corresponding GAMA model using the different layers.

**Comment by LBIRE** [comment]
Hi @erralb, thank you very much for pointing out the obsolescence of one of our tutorials. I have edited the said [tutorial](https://gama-platform.org/wiki/next/ManipulateOSMDatas) in several ways (fyi the wiki updates go on the "Next" tab in the top right corner, the former version will always appear in the 1.8.2-RC2 tab).

First, a new first step to install QuickOSM, a simple Plugin that will allow you to process the files downloaded from OSM website. 

Secondly, a guide for beginners in basic QGis treatment to select and clean up your layers. Of course, it is still GAMA documentation, therefore all features can't be detailed in our tutorials. If you are just discovering the QGis platform as of now, I invite you to explore the great QGis documentation available on their [official website] (https://www.qgis.org/fr/docs/index.html) as well as [QGis Tutorial](https://www.qgistutorials.com/en/) website, maintained and updated by the very active community of this open software. 

The tutorial you pointed out is not about getting through importation of shapefiles in GAMA since there are other thorough tutorials available. For instance, [this tutorial](https://gama-platform.org/wiki/LuneraysFlu_step3) I recommend if you are discovering the use of shapefiles in GAMA, and how to build your text model around it. 

I hope it will help you, thanks again for pointing it out !

**Comment by erralb** [comment]
Thank you very much !
