### ISSUE TITLE
Search is not working anymore

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama-platform.github.io#13]
The search filed ( top right of the website) does not work.
Note that it was working a few days ago!

When, using Google Chrome browser to open the website, and use the Inspect tool, each time I am looking for something, I have the following error message:

FINISHING INDEX
(index):3332 FINISHING INDEX ARCHITECTURES
(index):3334 FINISHING INDEX CONSTANTS
(index):3336 FINISHING INDEX LITERALS
lunr.js:2298 Uncaught TypeError: Cannot read property 'fieldVectors' of null
    at Function.lunr.Index.load (lunr.js:2298)
    at search ((index):3337)
    at checkEntry ((index):39)
    at HTMLInputElement.onkeypress ((index):21)
lunr.Index.load @ lunr.js:2298
search @ (index):3337
checkEntry @ (index):39
onkeypress @ (index):21

<img width="506" alt="capture d ecran 2018-08-12 a 16 59 30" src="https://user-images.githubusercontent.com/1555274/44003320-1d311086-9e51-11e8-8956-8c2c4baa80c3.png">

**Comment by dphilippon** [comment]
This is due to the indexes generated through Lunr that are not working (quite sure this is a JSON casting problem).

**Comment by benoitgaudou** [comment]
Do you have an idea how to fix it ?
I admit I have no idea of what you are talking about :-)

Le dim. 12 août 2018 à 17:06, Damien Philippon <notifications@github.com> a
écrit :

**Comment by dphilippon** [comment]
I checked that yesterday and it would seems that there is an error in the JSON. However, what is concerning is that the error would be at the **65,536** characters. I am currently wondering if that is not a size limit error (since we all know what does this number represent) for Lunr.JS or just being due to the size limit of one line (since it would seems that the whole JSON is written in one line). 
I'll try to go deeply in that way tonight.

**Comment by hqnghi88** [comment]
It works today (on firefox). Should we consider it as fixed?

**Comment by dphilippon** [comment]
Yeah, I forgot to close the issue when I took care of it (see commit https://github.com/gama-platform/gama-platform.github.io/commit/a746982a574158052e97a7fac4d46a9d2cf86848 )
