### ISSUE TITLE
broken link from 'geometry' to 'spatial operators'

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama-platform.github.io#141]
at https://gama-platform.org/wiki/DataTypes#geometry

**Exact broken link**

https://gama-platform.org/wiki/Operators#spatial-operators

**Expected link**

https://gama-platform.org/wiki/OperatorsNR#spatial-operators

**Comment by benoitgaudou** [comment]
In the page DataType, all the link now refer to the page OperatorsAA#... (to avoid changing the name each time we need to split the operators page ...).

By the way, previously there was on the GAMA site a single page for all operators (whereas on the wiki we need to split because of Github markdown limitations). @RoiArthurB @lesquoyb : do you whether this single page has been removed on purpose ?
