### ISSUE TITLE
Move version selector from topbar to sidebar

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#160]
The version selector is only useful for documentation, so it should only be visible in documentation and tutorials. Moving it to the sidebar would make it more explicit that it only concerns those parts

**Comment by AlexisDrogoul** [comment]
Is it going to be done today ? If not possible, I would advocate to remove it for the time being, temporarily, until it can be safely moved. @RoiArthurB

**Comment by RoiArthurB** [comment]
@AlexisDrogoul @lesquoyb 
Unfortunately, I can't figure out how to properly move it in the sidebar. It's a feature requested (?) since 2021 but not much development has been done on it since one of the maintainers proposed it. Only feature hacks are poorly documented, and I couldn't use them well (so I did comment and asked a bit here https://github.com/facebook/docusaurus/issues/5706#issuecomment-1524650708 )...

Anyway, I pushed my modifications on a separated branch as this feature can come later on, and we will hide the documentation versioning for now on and have only the latest 1.9.1 displayed :)

**Comment by RoiArthurB** [comment]
Thanks to slorber (Docusaurus' maintainer) we have a simple trick giving a good enough result :) 

![image](https://user-images.githubusercontent.com/16764085/235056798-65855248-8ec4-4796-ba18-bf36c8c16a67.png)

This is ready on the `sidebarVersion` branch :)

**Comment by AlexisDrogoul** [comment]
And is it possible to remove the emoji's please ??

**Comment by lesquoyb** [comment]
Reopening because it is not very satisfying on firefox:
![image](https://github.com/gama-platform/gama-platform.github.io/assets/6374469/89d13818-56d0-4904-95b1-b7bf22208710)
