### ISSUE TITLE
Add a reference to GAMA days 2022

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#170]
**Is your request related to a problem? Please describe.**
In the website there's a section about [past conferences](https://gama-platform.org/wiki/PreviousConferences), now that we have the proceedings of GAMA days 2022 we could add it there.
By the way is there any resource from GAMA days 2020 that we could add too ?

**Comment by RoiArthurB** [comment]
It would be great if it's possible to create a YT playlist with every talk which had been done during the GAMA Days 2022 and list the conference with this playlist. Maybe @chapuisk or @gnoubi can help to get those videos?

About the GAMA Days 2020, it has been planned, but never actually existed because of a little virus which popped into this world 😷😷😷

**Comment by lesquoyb** [comment]
Small update: I added the proceedings to hal-ird, and have been waiting for the document to be reviewed for a week or so now

**Comment by chapuisk** [comment]
@lesquoyb I've had this to my todo list ! I'll have time to do that before the end of the month. Cheers

**Comment by lesquoyb** [comment]
@chapuisk do you mean the video ? great !

The proceedings have just been accepted on HAL, so I updated the page with the link to it already :)

**Comment by lesquoyb** [comment]
I think we won't get the videos to this point so I'm closing the issue.
Please don't forget to record the sessions for this year's edition :)
