### ISSUE TITLE
Link does not lead to correct destination.

### ISSUE THREAD

**Issue by LorisHenry** [gama-platform/gama-platform.github.io#179]
On the page https://gama-platform.org/wiki/OperatorsSZ#color-related-operators
In the section color-related operators. Right clicking + Open in a new tab on gradient lead to the harmonic_mean operator documentation instead of the gradient operator documentation.

**To Reproduce**
1. Go to 'https://gama-platform.org/wiki/OperatorsSZ#color-related-operators'
2. Right Click + Open in a new tab on 'gradient' in the 'color-related operators' section
3. See error

**Expected behavior**
Should lead to https://gama-platform.org/wiki/OperatorsDH#gradient

- Browser : Chrome

**Comment by lesquoyb** [comment]
I can't reproduce the error, is it still happening @LorisHenry ?

**Comment by RoiArthurB** [comment]
I have it too and can't figure out what this bug comes from...

**Comment by AlexisDrogoul** [comment]
I can also reproduce it (right-clicking only; a left click seems ok -- and only on `gradient` !). It seems that the problem comes from the misalignment of anchors with the corresponding keyword on the page opened with a right-click when invoking `gradient`.  As a matter of fact, all the anchors are wrong on this page (a few symbols behind : for instance, the anchor next to `harmonic_mean` is `#gradient`, the one next to `gradient` is `#get_super_intention` and so on... )

**Comment by RoiArthurB** [comment]
@AlexisDrogoul This issue has been tracked down and is a Docusaurus problem (cf. issue linked above).

I'm not technical enough to explain briefly the cause of it, but the problem comes from the React page generator (we have too many link components) and we need to wait next major release of Docusaurus to have this issue fixed.

So, for now on, this issue is annoying but we can't fix it... :shrug:
