### ISSUE TITLE
collect search phrases from website

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama-platform.github.io#43]
I propose collecting all searched phrases from the GAMA website into a database. This database can then highlight most frequently used phrases. This will help us to improve the documentation on those operators, skills etc etc.

thank you

**Comment by RoiArthurB** [comment]
It's technically possible to collect that kind of data. But the actual search engine isn't build to display result based on probability.

Also, if we collect data, we'll have to create a page (Privacy Statement) explaining which data do we collect, how long do we keep them, how do we use them, and (the most important) we will have to respect RGPD. 
This last point is very heavy because we have to delete data from users who request us to delete them...

So we can discuss about it, but I'm afraid it will be very expensive (in time and human resources)
