### ISSUE TITLE
custom syntax highlighting of gaml code in github markdown

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama-platform.github.io#49]
Hi,

I have been wondering if it is possible to have some custom gaml highlighting for code blocks in github markdown. For example, if you use a code block ```code block``` with a language preference for r , it highlights r keywords as below 

```r
library(gaml)
k=mean(rnorm(100,1,0.1)
```

or for python as below:

```python
import numpy as n
float f = n.sin(90)
```

or java as below:

```java
import numpy
float f = n.sin(90);
```

Is it possible to create a custom syntax highlight for gaml language on github markdown? I do not know how easy or difficult it is, but could be nice in sharing or exhibiting code on github tutorials.

**Comment by RoiArthurB** [comment]
For the Github Wiki I'm afraid that it's impossible (mainly because we can't do any design more than the MarkDown Structure of the file).
But I'm working on it for the gama-platform website :)

**Comment by benoitgaudou** [comment]
Hi @RoiArthurB ,

Please find below a very small js tentative for GAML (rename it as .js).
[prism-gaml.txt](https://github.com/gama-platform/gama-platform.github.io/files/9782489/prism-gaml.txt)

If GAMA produces such a file you can use it on the website?

**Comment by RoiArthurB** [comment]
Hi @benoitgaudou ,

You're quick implementation does work good, see below : 

| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/16764085/195781118-4304e518-9a80-400f-a800-324e03156bfa.png) | ![image](https://user-images.githubusercontent.com/16764085/195781196-ca99ef5a-0c1e-4f04-b9fd-571b120c9e1b.png) |
| ![image](https://user-images.githubusercontent.com/16764085/195781032-2bf48043-5b4b-4618-a8ae-82fdf0df9946.png) | ![image](https://user-images.githubusercontent.com/16764085/195780913-72bb5cff-5dff-498a-92b7-b87be27d8a01.png) |

So if you can generate this file from GAMA, I'll be easily able to integrate it during the website compilation 👌

I also made the branch [syntax-gaml](https://github.com/gama-platform/gama-platform.github.io/tree/syntax-gaml) to work on it :)

**Comment by benoitgaudou** [comment]
Thanks! 
I am not so impressed by the after version : it was supposed to highlight the statement names also ... but get italic instead, I guess it is mainly due to the css ...
Thanks for the integration and for the branch.... but how to use this new branch ? I can produce the website by myself locally ?

**Comment by RoiArthurB** [comment]
@benoitgaudou 

>  I am not so impressed by the after version : it was supposed to highlight the statement names also ... but get italic instead, I guess it is mainly due to the css ...

Yes, we probably can also tweak the color theme or badly used the syntax to just have appropriate colors on the wiki 🤷 But it's minor tweaking in my point of view :) 

>  Thanks for the integration and for the branch.... but how to use this new branch ? I can produce the website by myself locally ?

Yes you can, it's a little tricky so either we can do it together, otherwise it's mostly following step-by-step the github action here : https://github.com/gama-platform/gama-platform.github.io/blob/sources/.github/workflows/github-travis.yml

You'll need to have Python3, pip (package manager for Python), NodeJS, yarn (or npm; both package managers for NodeJS) and bash - I know it's a bit heavy and complex 😅😅

**Comment by RoiArthurB** [comment]
Re-opening to work on full Github's syntax support color (forgot that initial issue request 🙈)
