### ISSUE TITLE
Put the Paper referencing GAMA more visible

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#60]
There is a nice page (I think made by Quang during the coding camp) with all the paper that cites GAMA however it's very hard to find in the website (at the very end of this page).

https://gama-platform.github.io/wiki/Contribute

Could be nice to find a way to put it more visible?

**Comment by RoiArthurB** [comment]
Are you talking about that page https://gama-platform.github.io/wiki/References ?
If yes, the page is linked in the sidebar Scientific References > References

Otherwise, please send me a link to the page you're talking about

**Comment by agrignard** [comment]
yes I was speaking about this one that I was actually accessing though this https://gama-platform.github.io/wiki/Contribute and it was at the very end. So ok in the side bar it's better

Right now we have this
<img width="259" alt="Screen Shot 2019-06-06 at 09 16 14" src="https://user-images.githubusercontent.com/3928502/59035683-ccaf4f80-883b-11e9-8b63-ad47e152b7f1.png">

Does it make sense to have this double hierarchy? Is it a place older for other references?

**Comment by RoiArthurB** [comment]
Ok perfect, so I can close the issue.

About the double hierarchy, I had to compose with Docusaurus. On the default architecture of the Sidebar, every link should be under a _Big title_ (here "Scientific References"). So if I want to just have this big title clickable, I have to tweak the website after it's been generated.
So for now I keep it like this because it's easier for me. But I want to remove that useless menu for primary object like this one.
