### ISSUE TITLE
Link to a JDK in the download website

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#63]
What about having a link to the right jdk to download here
https://gama-platform.github.io/download

I mean for beginner user that don't even know what is a jdk it's a bit difficult to know where to find it.

**Comment by benoitgaudou** [comment]
Hi all,

I agree with Arnaud that the Download, as it is now, could be misleading as
a random user will have the tendency to download the first link (Download)
whereas the one with JDK
is definitely the safer for normal users.

What do you think to present the download as following :
- Download      (that will contain the version of GAMA with the JDK)
- Download Light Version     (or something like that) and add a link with a
page explaining the install of the JDK
- Daily version

I interact in the last week with 2 or 3 users that download this version
and they are able to run it...
but GAMA in this case is not able to manage properly shapefiles.

Cheers

Benoit

Le sam. 8 juin 2019 à 01:49, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by AlexisDrogoul** [comment]
@benoitgaudou what do you mean by `GAMA in this case is not able to manage properly shapefiles` ? Which version are you talking about ? What it is this bug ? If the daily build is broken so is, virtually, GAMA 1.8...

Regarding the JDK / no JDK, I get the point, but I see at least 3 problems: 

- redistributing a JDK means we are (normally) bound to maintain this JDK in order to offer users a version which does not contain security flaws, etc. What if someone is attacked because running GAMA on its machine has executed a JDK lacking the latest security patches ? It is not his/her responsibility anymore, it becomes ours. Do we want to issue a new release every 2/3 months to work around this potential problem ? Not sure.
- all the problems we had recently came from versions with JDK (not properly configured, etc. , see again https://github.com/gama-platform/gama/issues/2764 this morning). Putting forward this version is maybe not the best strategy. I'm much more comfortable with a page that explains how to install the JDK than by discovering such bugs after a release !
- the size is another matter. First of all, it is not indicated on the Downloads page, and it should be (on each button). Not sure if it is possible to get it automatically, though. But having to download 380MB instead of 135MB for a "default" version is clearly not the same when your Internet speed is not very good.


So, even if I prefer very simple pages with as little text as possible, my preference would go to a small text explaining clearly the difference between the versions. Or is it possible to have it as a pop-up text on each button ? Something like:

- Install this version if you already have an Oracle JDK v. 1.8 installed on your computer. If you're not sure, check here -- link to Oracle online verification if it exists ?? --
- Install this version if you don't want to install Oracle JDK by yourself. Be aware, though, that the version of Java included should not be used to run another software than GAMA -- or some similar legal warning --
- Install this version if you feel adventurous. Contains the latest updates to GAMA, but some might not be fully tested -- or something similar -- 

What's your opinion on this @gama-platform/committers  ?

**Comment by benoitgaudou** [comment]
Hi Alexis,

About the first point, here is the context:
I have a student with a Ubuntu (I do not know the Java version, neither
whether it is openjdk or Oracle).
He has downloaded the "official" GAMA 1.8 release, withtout JDK.
When it worked GAMA, no problem appears, he was able to do Schelling model
and Prey-predator one.

But when we had started Traffic model, and have a look at the shapefile :
- GAMA was not able to display them (in the Shapefile Viewer). The view
opened with a red cross icon and a GAMA / Java Exception appearing in it.
- When we look at the file in the model explorer, instead of :

[image: Capture d’écran 2019-06-08 à 08.40.50.png]

We had 0 object in each of the 3 files.

So I asked him to download the same version of GAMA but WITH the JDK, and
it worked as a charm.

Notice that I met yesterday another student with similar problem and
similar install (GAMA withtout JDK).
So I also advice him to take the one with JDK.

My diagnosis was thus that the version of Java was wrong...

Cheers

Benoit


Le sam. 8 juin 2019 à 07:52, Alexis Drogoul <notifications@github.com> a
écrit :

**Comment by hqnghi88** [comment]
Hello Benoit, just a quick comment (i need time to read this long conversation), for ubuntu 18+ , it seem to be very hard to install oracle jdk 8 as oracle remove jdk 8 on it ppa (which was easy to install with apt-get) so if your students have a jdk, probably it is openjdk or oracle jdk 9+.

**Comment by hqnghi88** [comment]
Dear @AlexisDrogoul , i did not receive email on this repo so may be your tag gama-platform/committers would not work?
About jdk , i agree with your 3 problems. But the status of java version is really crazy as it is now starting to deprecate  java 9 - somewhere, and soon, everywhere so 1.8 is nearly its endtime. I propose in this release, could it better to have a check when gama start, the version of java installed and show the message box to say the instruction (or even close gama :D) than a web page?

**Comment by benoitgaudou** [comment]
Hi all,

Given the Wikipedia page, we have until Dec. 2020 before the Javapocalypse
https://en.wikipedia.org/wiki/Java_version_history

Definitely, I agree on the fact that somewhere the Java version should
checked by GAMA and that this information should be available somewhere (or
launch some warning).
In addition, to ease the debug it could be great to have a more precise
information in the window "About GAMA" : for the moment the user can only
see that it is using GAMA 1.8.0.
Which is not precise enough (cf. an example on the GAMA list).

Cheers


Benoit



Le sam. 8 juin 2019 à 10:33, HUYNH Quang-Nghi <notifications@github.com> a
écrit :

**Comment by benoitgaudou** [comment]
Dear all,

My 2 cents in the discussion about putting forward GAMA with JDK or without
JDK.
- I am not sure that the size is really a problem now. Internet access has
improved. From the training sessions in the last year(s), I always ask the
students to download the with JDK version.
And I have the feeling that either the network was good enough to get the
350MB version, of it is bad and we cannot even get the 135MB version.
In addition, from a practical point of view, if people download GAMA 135MB
AND the Java JDK, do they not download around 350MB at the end ?

- When we ask users to download and install by themselves Java, first it is
always error-prone (between JRE and JDK, which version is used by default,
Nghi says that the install of the JDK 1.8 is now painful on Ubuntu ...) but
also we "force" them to use another Java than the one they used. In fact we
let a huge footprint in user systems. It could be possible that they have
to switch between Java versions when using various softwares.
Many of the GAMA users are not really computer scientists, and I have the
feeling that it will a lot of pain for them...

In fact, as you mentionned, from my point of view, the best way would be to
improve the update mechanism of GAMA.
In order to be allow an automatic update of GAMA when a new JDK patch has
been released and that we produced a new patched release.

Otherwise, I think that we need to be extremely clear on the pros and
counts of each version (advanced user vs newbie, ... ).

Cheers

Benoit

Le sam. 8 juin 2019 à 07:52, Alexis Drogoul <notifications@github.com> a
écrit :

**Comment by sriramab** [comment]
There are two high visible areas on the forum , prime real estate , where couple of sentences can be written to state exactly: 

```
Gama RC tested on oracle java 1.10_981uf
Gama 1.8_edfgt8 tested on Oracle java 1.9_654u

If you have installed any other combinations of Gama or java,
please read this page very carefully  http://gama.zx/blahblah/installing-java

```
The advantage on putting this on forum notice board is , the user can see this before posting a question. 

These two locations are very effective, because :- 

First is the forum notice board
- There have been no non-English message on the firm since I put a notice that forum is only in English

- People no longer post multiple messages, because they know that all messages are moderated and they should wait a while to see their posts on the forum. 


The second prime estate is a pinned post on the forum

**Comment by ptaillandier** [comment]
Hi all,

For me, the JDK version should be the first one on the list. To be honest,
this version has changed my life: now, training sessions (and in particular
short ones) are so much easier to give... no more problem with GAMA that
does not work (because of java version). In addition, I am pretty sure that
many users give just one chance to a software: if it does not work
directly, they will not try to solve the issue, and just consider that the
software as defective. It's not for nothing that Netlogo has an embedded
Java version.

But I understand the argument of Alexis, and I agree with the idea of
adding information (in particular for legal issues).

Patrick

**Comment by AlexisDrogoul** [comment]
All right then. Lets put the JDK version first, with 2 things: an indication of the size (e.g. `WITH JDK (320MB)`, `WITHOUT JDK (125 MB)`, `DAILY`) and the possibility to display text below when hovering over a button. Something like this  ?
<img width="552" alt="GAMA-Platform · GAMA 2019-06-09 18-53-44" src="https://user-images.githubusercontent.com/579256/59158759-62bbd200-8ae9-11e9-94d3-1f5ebbe2e794.png">

**Comment by RoiArthurB** [comment]
Buttons should be fixed on the last commit f05cae9f3cb1011a8e6a7c7c84441c409e7712ad

I'll work on the box later. I don't know if I can display a pop-up on top of the button or if I'll display a box somewhere else on the page.

Another solution could be to add a pop-up after clicking with the text warning and launch download with a "I understand risk" :thinking:

**Comment by RoiArthurB** [comment]
@AlexisDrogoul I can add a tooltip above buttons when we hover it with the mouse :

Here's an example with short text
![2019-06-24-100520_1366x768_scrot](https://user-images.githubusercontent.com/16764085/59989048-a37a2600-9667-11e9-838d-e08c0ce6c095.png)
Here's an example with longer text
![2019-06-24-100525_1366x768_scrot](https://user-images.githubusercontent.com/16764085/59989049-a37a2600-9667-11e9-957d-80af115faceb.png)


I can add it on every buttons with custom text if you want, just give me text for each :)

**Comment by hqnghi88** [comment]
Tooltips is ok for me but the text should be more informative, bold the important or even red color and not  capital all paragraph .

**Comment by RoiArthurB** [comment]
Sure, I just added some random text just to see the display.
Also, tooltips can have the color of the button hovered ... :thinking:

**Comment by RoiArthurB** [comment]
I've implement tooltips in the last commit bc8aec83ba0a72112eb9b026281aedf59bc331dc
Tell me what you think about it (in 10 minutes, the site should compile first) and close the issue if it's do the job :smile:

**Comment by AlexisDrogoul** [comment]
Very nice. The skull heads are a bit too much IMO. 
SDK Text should say: "This is the easiest version to run. No need to install anything more. Note that the embedded JDK should not be used to run other softwares". 
Regarding the sizes, are you able to gather them or is it fixed ? Because the new sizes are way smaller...

**Comment by RoiArthurB** [comment]
Here's with the new text : 
![2019-06-24-140744_1366x768_scrot](https://user-images.githubusercontent.com/16764085/59998384-763e6f80-9689-11e9-85df-6d2cebfb1abc.png)
And the text is the same size as any text in pages (14px), I don't think that we should change it but it's possible to make it bigger. Do you want to?

**Comment by agrignard** [comment]
Great!

**Comment by RoiArthurB** [comment]
I think that this tooltips with the PDF button is a little overkill, but why not.
However the PDF button will remain disable until the documentation will be generated :)
