### ISSUE TITLE
Download buttons

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama-platform.github.io#64]
In parallel to the discussion about the download page in issue #63, I notice that:
- the "With JDK" for MacOSX does not work
- the 3 buttons "DAILY" are only a link to the github page, which is surprising for a visitor of the website.

Benoit

**Comment by AlexisDrogoul** [comment]
First link is effectively broken. Point to `https://github.com/gama-platform/gama/releases/download/latest/GAMA1.8_Official_withJDK_Mac_64bits.zip`, while the correct address is `https://github.com/gama-platform/gama/releases/download/latest/GAMA1.8_Official_withJDK_MacOS_64bits.zip` (notice the additional 'OS'). However, it is the script that creates the releases which is incorrect, since the name of the regular download contains `Mac` and not `MacOS`. @hqnghi88 ?
Second is a design choice. So that people understand they are not in "normal Download page" anymore.

**Comment by hqnghi88** [comment]
Well, easy to change, just to know what us the right name because i. Rc1 rc2 it was macos. But yes, win and Linux dont have that suffix.
