### ISSUE TITLE
Link broken or useless

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#68]
https://gama-platform.github.io/wiki/Tutorials#predator-prey-tutorial

**Comment by RoiArthurB** [comment]
Hi, could you explain me where you find the URL, and where it should point to (if you remember) ? :)
Otherwise, what I see from your URL is an HTML anchor to the Predator Tutorial title on the Tutorials page. So the correct URL is this one : https://gama-platform.github.io/wiki/Tutorials#predator-prey-tutorial-predatorprey

**Comment by agrignard** [comment]
I was refering to the url link at the beginning of the page that doesn't seems to have any effect
<img width="820" alt="Capture d’écran 2019-08-13 à 22 02 09" src="https://user-images.githubusercontent.com/3928502/62973339-2d4ba180-be16-11e9-9761-8a74084bbfb1.png">

**Comment by RoiArthurB** [comment]
Could you, please, send me the link you where on and not just a simple screenshot ? I can't click on links and check page's information on that screenshot 🙊🙊

**Comment by RoiArthurB** [comment]
Fix - will appear on the next website generation -
