### ISSUE TITLE
Automated updating ? 

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama-platform.github.io#8]
Hi,

Does the automated updating of the wiki + the GitHub.io websites work ? I understood it should be handled by Travis, but I've added some artifacts to GAML recently and they dont show up anywhere. 

Alexis

**Comment by hqnghi88** [comment]
Dear Alexis, Damien must confirm the contents of operators or gaml artifacts but i know that travis works well still now for generation, even the link to continous build is updated correctly.

**Comment by hqnghi88** [comment]
I found that the "super" is on https://gama-platform.github.io/wiki/PseudoVariables

**Comment by AlexisDrogoul** [comment]
Yep. Because I edited the wiki. But my concern is about artefacts added in the code: are the wiki files automatically regenerated when I change something in the Java code + annotations ?

**Comment by hqnghi88** [comment]
I'm afraid it was not. @dphilippon do you know where is the generator of operatora artifacts?

**Comment by dphilippon** [comment]
That's a good question. Was it not done before when building a new version of Gama after a commit and Travis build pass ?

**Comment by hqnghi88** [comment]
mission accepted

**Comment by hqnghi88** [comment]
mission accomplished. The artifacts is now regenerated by "ci docs" or in the cron. Please recheck your added artifacts.

**Comment by AlexisDrogoul** [comment]
Well done. I have checked and they are not all there (for example the `invoke` statement, an other form of `do`, is not present, but maybe is it a bug in the documentation regarding multiple names of statements ?), but some are already both in the wiki and in the doc, which means it works ! I think we can close this issue now.

**Comment by hqnghi88** [comment]
Dear Alexis,
May be yes, because i found in singleequationstatement, the doc annotation
was not good. It was @ operator( ... , doc=@doc ()) , it must be outside
@operator , like @operator() @doc(value=""))


On Jul 24, 2017 12:26, "Alexis Drogoul" <notifications@github.com> wrote:

Well done. I have checked and they are not all there (for example the invoke
statement, an other form of do, is not present, but maybe is it a bug in
the documentation regarding multiple names of statements ?), but some are
already both in the wiki and in the doc, which means it works ! I think we
can close this issue now.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/gama-platform/gama-platform.github.io/issues/8#issuecomment-317322641>,
or mute the thread
